-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9\Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9_pkg.vhd
-- Created: 2021-08-24 10:29:19
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9_pkg IS
  TYPE vector_of_signed8 IS ARRAY (NATURAL RANGE <>) OF signed(7 DOWNTO 0);
END Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9_pkg;

