-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9\Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9.vhd
-- Created: 2021-08-24 10:29:19
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: 0
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9
-- Source Path: Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9 IS
  PORT( clk                               :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8_En4
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- sfix8_En7
        );
END Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9;


ARCHITECTURE rtl OF Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9 IS

  -- Component Declarations
  COMPONENT Source
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8_En4
          Out1                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- sfix8_En7
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Source
    USE ENTITY work.Source(rtl);

  -- Signals
  SIGNAL Source_out1                      : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  -- This block was created using function approximation.
  u_Source : Source
    PORT MAP( clk => clk,
              enb => clk_enable,
              In1 => In1,  -- sfix8_En4
              Out1 => Source_out1  -- sfix8_En7
              );

  ce_out <= clk_enable;

  Out1 <= Source_out1;

END rtl;

