-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9\Source.vhd
-- Created: 2021-08-24 10:29:18
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Source
-- Source Path: Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9/Source
-- Hierarchy Level: 1
-- 
-- Simulink subsystem description for Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9/Source:
-- 
-- This block was created using function approximation.
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Approximate_id_0af2ac3f3b928182f3ff557fc379a1d7491938e9_pkg.ALL;

ENTITY Source IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(7 DOWNTO 0);  -- sfix8_En4
        Out1                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- sfix8_En7
        );
END Source;


ARCHITECTURE rtl OF Source IS

  -- Constants
  CONSTANT LUT_data                       : vector_of_signed8(0 TO 158) := 
    (to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8),
     to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8),
     to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8),
     to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8),
     to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8),
     to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8),
     to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8),
     to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#80#, 8), to_signed(-16#7F#, 8),
     to_signed(-16#7F#, 8), to_signed(-16#7F#, 8), to_signed(-16#7F#, 8), to_signed(-16#7F#, 8),
     to_signed(-16#7F#, 8), to_signed(-16#7F#, 8), to_signed(-16#7F#, 8), to_signed(-16#7E#, 8),
     to_signed(-16#7E#, 8), to_signed(-16#7E#, 8), to_signed(-16#7E#, 8), to_signed(-16#7E#, 8),
     to_signed(-16#7D#, 8), to_signed(-16#7D#, 8), to_signed(-16#7C#, 8), to_signed(-16#7C#, 8),
     to_signed(-16#7B#, 8), to_signed(-16#7B#, 8), to_signed(-16#7A#, 8), to_signed(-16#79#, 8),
     to_signed(-16#78#, 8), to_signed(-16#78#, 8), to_signed(-16#76#, 8), to_signed(-16#75#, 8),
     to_signed(-16#74#, 8), to_signed(-16#72#, 8), to_signed(-16#71#, 8), to_signed(-16#6F#, 8),
     to_signed(-16#6D#, 8), to_signed(-16#6A#, 8), to_signed(-16#68#, 8), to_signed(-16#65#, 8),
     to_signed(-16#61#, 8), to_signed(-16#5E#, 8), to_signed(-16#5A#, 8), to_signed(-16#56#, 8),
     to_signed(-16#51#, 8), to_signed(-16#4C#, 8), to_signed(-16#47#, 8), to_signed(-16#41#, 8),
     to_signed(-16#3B#, 8), to_signed(-16#35#, 8), to_signed(-16#2E#, 8), to_signed(-16#27#, 8),
     to_signed(-16#1F#, 8), to_signed(-16#18#, 8), to_signed(-16#10#, 8), to_signed(-16#08#, 8),
     to_signed(16#00#, 8), to_signed(16#08#, 8), to_signed(16#10#, 8), to_signed(16#18#, 8), to_signed(16#1F#, 8),
     to_signed(16#27#, 8), to_signed(16#2E#, 8), to_signed(16#35#, 8), to_signed(16#3B#, 8), to_signed(16#41#, 8),
     to_signed(16#47#, 8), to_signed(16#4C#, 8), to_signed(16#51#, 8), to_signed(16#56#, 8), to_signed(16#5A#, 8),
     to_signed(16#5E#, 8), to_signed(16#61#, 8), to_signed(16#65#, 8), to_signed(16#68#, 8), to_signed(16#6A#, 8),
     to_signed(16#6D#, 8), to_signed(16#6F#, 8), to_signed(16#71#, 8), to_signed(16#72#, 8), to_signed(16#74#, 8),
     to_signed(16#75#, 8), to_signed(16#76#, 8), to_signed(16#78#, 8), to_signed(16#78#, 8), to_signed(16#79#, 8),
     to_signed(16#7A#, 8), to_signed(16#7B#, 8), to_signed(16#7B#, 8), to_signed(16#7C#, 8), to_signed(16#7C#, 8),
     to_signed(16#7D#, 8), to_signed(16#7D#, 8), to_signed(16#7E#, 8), to_signed(16#7E#, 8), to_signed(16#7E#, 8),
     to_signed(16#7E#, 8), to_signed(16#7E#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8),
     to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8), to_signed(16#7F#, 8));  -- sfix8 [159]

  -- Signals
  SIGNAL In1_signed                       : signed(7 DOWNTO 0);  -- sfix8_En4
  SIGNAL LUT_k                            : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL LUT_sub_temp                     : signed(7 DOWNTO 0);  -- sfix8
  SIGNAL LUT_out1                         : signed(7 DOWNTO 0);  -- sfix8_En7
  SIGNAL LUT_out1_1                       : signed(7 DOWNTO 0) := to_signed(16#00#, 8);  -- sfix8_En7

BEGIN
  In1_signed <= signed(In1);

  LUT_sub_temp <= In1_signed - to_signed(-16#50#, 8);
  
  LUT_k <= to_unsigned(16#00#, 8) WHEN In1_signed <= to_signed(-16#50#, 8) ELSE
      to_unsigned(16#9E#, 8) WHEN In1_signed >= to_signed(16#4E#, 8) ELSE
      unsigned(LUT_sub_temp);
  LUT_out1 <= LUT_data(to_integer(LUT_k));

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        LUT_out1_1 <= LUT_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  Out1 <= std_logic_vector(LUT_out1_1);

END rtl;

